# Generated by Django 5.0.2 on 2024-03-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firsname',
            new_name='firstname',
        ),
    ]
